# Generated by Django 4.2.6 on 2023-11-01 17:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_image', models.ImageField(upload_to='blogImage/')),
                ('blog_description', tinymce.models.HTMLField()),
            ],
        ),
    ]
