# Generated by Django 4.2.6 on 2023-11-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
