# Generated by Django 4.2.6 on 2023-11-04 13:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_blog_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='blog_title'),
        ),
    ]
