# Generated by Django 4.2.6 on 2023-11-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='slug',
            new_name='blog_slug',
        ),
    ]
